/* PositionReader.hpp
 * 
 * A code that reads the dump/position files generated by LAMMPS.
 */

#ifndef POSITIONREADER_HPP
#define POSITIONREADER_HPP

#include <iostream>
#include <vector>
#include <string>

using std::vector;
using std::string;
using std::ifstream;

class PositionReader {

private:
  
  int numOfBeads {};
  vector<double> boxSize {};
  long timeInc {}, time {};
  string positionFile {};
  bool fileOpen {false};
  ifstream reader;
  
  // For storing bead position and type data 
  vector<vector<double> >* position;
  vector<vector<int> >* boundaryCount;
  vector<int>* type;

  void initData();
  void deleteData();

public:
  
  // Destructor
  ~PositionReader();
  
  // Load a new position file
  bool open(string positionFile, int numOfBeads, 
	    double lx, double ly, double lz, int timeInc);
  void close();

  // Return the position of a bead
  double getPosition(int beadIndex, int comp) const;
  double getUnwrappedPosition(int beadIndex, int comp) const;

  // Return the type of a bead
  int getType(int beadIndex) const;

  // Retrieve the bead position data in the next time frame
  // Return false if there is no next frame
  bool nextFrame();
  
  // Get the time associated with the frame
  long getTime() const;

  // Check if there is a file open
  bool isOpen();
  
};

#endif
